CREATE TABLE t01_solicitudes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    estado        INTEGER,
    fecha_ingreso date,
    monto         DOUBLE PRECISION,
    id_cliente    INTEGER,
    CONSTRAINT pk_t01_solicitudes PRIMARY KEY (id)
);

ALTER TABLE t01_solicitudes
    ADD CONSTRAINT uc_t01_solicitudes_id_cliente UNIQUE (id_cliente);
